services:
  portage-api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages/shared/src:/app/packages/shared/src

